apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - issuer.yaml
  - pomodoro.yaml
  - imageregistry.yaml
  - imagepolicy.yaml
  - imageupdateautomation.yaml
